[2025-05-19T07:28:43.564+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-19T07:28:43.627+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_price_pipeline.validate_data manual__2025-05-19T07:28:22.740128+00:00 [queued]>
[2025-05-19T07:28:43.646+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_price_pipeline.validate_data manual__2025-05-19T07:28:22.740128+00:00 [queued]>
[2025-05-19T07:28:43.647+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-05-19T07:28:43.666+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): validate_data> on 2025-05-19 07:28:22.740128+00:00
[2025-05-19T07:28:43.722+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=202) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-19T07:28:43.724+0000] {standard_task_runner.py:64} INFO - Started process 204 to run task
[2025-05-19T07:28:43.742+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_price_pipeline', 'validate_data', 'manual__2025-05-19T07:28:22.740128+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/flight_price_pipeline.py', '--cfg-path', '/tmp/tmpsfq3nqap']
[2025-05-19T07:28:43.752+0000] {standard_task_runner.py:91} INFO - Job 3: Subtask validate_data
[2025-05-19T07:28:43.916+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_price_pipeline.validate_data manual__2025-05-19T07:28:22.740128+00:00 [running]> on host 286fd7c1dbed
[2025-05-19T07:28:44.052+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_price_pipeline' AIRFLOW_CTX_TASK_ID='validate_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T07:28:22.740128+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T07:28:22.740128+00:00'
[2025-05-19T07:28:44.054+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-19T07:28:44.079+0000] {validation.py:36} INFO - Start validation for table flight_prices_raw
[2025-05-19T07:28:46.338+0000] {validation.py:48} INFO - Read 57000 rows from flight_prices_raw table
[2025-05-19T07:28:46.429+0000] {validation.py:107} WARNING - Found 10930 rows with invalid seasonality values
[2025-05-19T07:28:47.201+0000] {validation.py:125} INFO - Flagged 10930 invalid records in flight_prices_raw_invalid_records
[2025-05-19T07:28:47.203+0000] {validation.py:130} INFO - Validation completed successfully for table flight_prices_raw
[2025-05-19T07:28:47.206+0000] {python.py:237} INFO - Done. Returned value was: True
[2025-05-19T07:28:47.209+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-19T07:28:47.266+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=flight_price_pipeline, task_id=validate_data, run_id=manual__2025-05-19T07:28:22.740128+00:00, execution_date=20250519T072822, start_date=20250519T072843, end_date=20250519T072847
[2025-05-19T07:28:47.333+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2025-05-19T07:28:47.383+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-05-19T07:28:47.384+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
