[2025-05-19T07:29:01.446+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-19T07:29:01.479+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: flight_price_pipeline.load_to_postgres manual__2025-05-19T07:28:22.740128+00:00 [queued]>
[2025-05-19T07:29:01.484+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: flight_price_pipeline.load_to_postgres manual__2025-05-19T07:28:22.740128+00:00 [queued]>
[2025-05-19T07:29:01.484+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 3
[2025-05-19T07:29:01.496+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_to_postgres> on 2025-05-19 07:28:22.740128+00:00
[2025-05-19T07:29:01.509+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'flight_price_pipeline', 'load_to_postgres', 'manual__2025-05-19T07:28:22.740128+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/flight_price_pipeline.py', '--cfg-path', '/tmp/tmp3jw1eb1t']
[2025-05-19T07:29:01.513+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask load_to_postgres
[2025-05-19T07:29:01.512+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=214) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-05-19T07:29:01.515+0000] {standard_task_runner.py:64} INFO - Started process 216 to run task
[2025-05-19T07:29:01.560+0000] {task_command.py:426} INFO - Running <TaskInstance: flight_price_pipeline.load_to_postgres manual__2025-05-19T07:28:22.740128+00:00 [running]> on host 286fd7c1dbed
[2025-05-19T07:29:02.545+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='flight_price_pipeline' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-05-19T07:28:22.740128+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-19T07:28:22.740128+00:00'
[2025-05-19T07:29:02.547+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-19T07:29:02.560+0000] {loading.py:35} INFO - Starting data loading from MYSQL table flight_prices_raw_transformed to PostgreSQL
[2025-05-19T07:29:07.311+0000] {loading.py:60} INFO - Loaded 57000 rows from MySQL flight_prices_raw_transformed to PostgreSQL
[2025-05-19T07:29:07.318+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-19T07:29:07.321+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/scripts/loading.py", line 75, in load_to_postgres
    kpi_df = kpis.get(kpi_name)
             ^^^^^^^^
AttributeError: 'str' object has no attribute 'get'
[2025-05-19T07:29:07.362+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=flight_price_pipeline, task_id=load_to_postgres, run_id=manual__2025-05-19T07:28:22.740128+00:00, execution_date=20250519T072822, start_date=20250519T072901, end_date=20250519T072907
[2025-05-19T07:29:07.391+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task load_to_postgres ('str' object has no attribute 'get'; 216)
[2025-05-19T07:29:07.439+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2025-05-19T07:29:07.489+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-19T07:29:07.491+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
